name: Build and deploy GH Pages
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build_and_deploy
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: main
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
